## 파이토치의 구성요소

- `torch`: 메인 네임스페이스, 텐서 등의 다양한 수학 함수가 포함
- `torch.autograd`: 자동 미분 기능을 제공하는 라이브러리
- `torch.nn`: 신경망 구축을 위한 데이터 구조나 레이어 등의 라이브러리
- `torch.multiprocessing`: 병럴처리 기능을 제공하는 라이브러리
- `torch.optim`: SGD(Stochastic Gradient Descent)를 중심으로 한 파라미터 최적화 알고리즘 제공
- `torch.utils`: 데이터 조작 등 유틸리티 기능 제공
- `torch.onnx`: ONNX(Open Neural Network Exchange), 서로 다른 프레임워크 간의 모델을 공유할 때 사용

## 텐서(Tensors)

* 데이터 표현을 위한 기본 구조로 텐서(tensor)를 사용
* 텐서는 데이터를 담기위한 컨테이너(container)로서 일반적으로 수치형 데이터를 저장
* 넘파이(NumPy)의 ndarray와 유사
* GPU를 사용한 연산 가속 가능

In [1]:
import torch

x = torch.empty(4,2)
print(x)    # 값은 초기화되지 않은 값이 들어감

x = torch.rand(4,2)
print(x)    # 랜덤을 기준으로 초기화됨

x = torch.zeros(4,2, dtype = torch.long)
print(x)

x = torch.tensor([3, 2.3])
print(x)      # 사용자가 입력한 값으로 텐서 초기화

x = x.new_ones(2,4, dtype = torch.double)
print(x)    # 2 x 4 크기 double타입, 1로 채워진 텐서

x = torch.rand_like(x, dtype=torch.float)
print(x)    # x와 같은 크기ㅣ, float타입, 무작위로 채워진 텐서

print(x.size())

tensor([[-2.2035e+30,  4.5654e-41],
        [-2.2063e+30,  4.5654e-41],
        [-2.2065e+30,  4.5654e-41],
        [-2.2064e+30,  4.5654e-41]])
tensor([[0.8968, 0.1287],
        [0.5580, 0.8791],
        [0.5157, 0.5239],
        [0.9210, 0.9151]])
tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])
tensor([3.0000, 2.3000])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
tensor([[0.9553, 0.2500, 0.4033, 0.5998],
        [0.1418, 0.7935, 0.5425, 0.0640]])
torch.Size([2, 4])


In [ ]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

print(ft.short())   # 기존 데이터타입을 바꿔버림
print(ft.int())
print(ft.long())

tensor([1., 2., 3.])
torch.float32
tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


### CUDA Tensors

- `.to` 메소드를 사용하여 텐서를 어떠한 장치(cpu, gpu)로도 옮길 수 있음

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

device =  torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device = device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))

tensor([0.5168])
0.5168253779411316
torch.float32
cpu
tensor([1.])
tensor([0.5168])
tensor([1.5168])
tensor([1.5168], dtype=torch.float64)


### 다차원 텐서

In [ ]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

t2 = torch.tensor([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(t2.ndim)
print(t2.shape)
print(t2)

t3 = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                  [[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                  [[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

0
torch.Size([])
tensor(0)
1
torch.Size([3])
tensor([1, 2, 3])
2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


### 텐서 연산

In [ ]:
import math

a = torch.rand(1,2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.floor(a))
print(torch.ceil(a))
print(torch.clamp(a, -0.5, 0.5))

print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,2])))


tensor([[0.5322, 0.3543]])
tensor([[0.5322, 0.3543]])
tensor([[0., 0.]])
tensor([[1., 1.]])
tensor([[0.5000, 0.3543]])
tensor([[0.5322, 0.3543]])
tensor(0.3543)
tensor(0.5322)
tensor(0.4433)
tensor(0.1258)
tensor(0.1886)
tensor([1, 2, 3])


In [ ]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.9514, 0.7460],
        [0.7653, 0.2723]])
tensor([[0.4182, 0.2132],
        [0.5946, 0.5566]])


In [ ]:
print(x+y)
print(torch.add(x,y))

# 결과를 텐서 인자로 받는 법
result = torch.empty(2,4)
torch.add(x,y, out = result)
print(result)

tensor([[1.3696, 0.9592],
        [1.3599, 0.8289]])
tensor([[1.3696, 0.9592],
        [1.3599, 0.8289]])
tensor([[1.3696, 0.9592],
        [1.3599, 0.8289]])


<ipython-input-12-d4832d94a866>:6: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  torch.add(x,y, out = result)


In [ ]:
# 뺄셈
print(x)
print(y)
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))


tensor([[0.9514, 0.7460],
        [0.7653, 0.2723]])
tensor([[0.4182, 0.2132],
        [0.5946, 0.5566]])
tensor([[ 0.5332,  0.5328],
        [ 0.1708, -0.2843]])
tensor([[ 0.5332,  0.5328],
        [ 0.1708, -0.2843]])
tensor([[ 0.5332,  0.5328],
        [ 0.1708, -0.2843]])


In [ ]:
# 곱셈
print(x)
print(y)
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[0.9514, 0.7460],
        [0.7653, 0.2723]])
tensor([[0.4182, 0.2132],
        [0.5946, 0.5566]])
tensor([[0.3979, 0.1591],
        [0.4550, 0.1516]])
tensor([[0.3979, 0.1591],
        [0.4550, 0.1516]])
tensor([[0.3979, 0.1591],
        [0.4550, 0.1516]])


In [ ]:
# 나눗셈
print(x)
print(y)
print(x / y)
print(torch.div(x,y))
print(x.div(y))

tensor([[0.9514, 0.7460],
        [0.7653, 0.2723]])
tensor([[0.4182, 0.2132],
        [0.5946, 0.5566]])
tensor([[2.2752, 3.4986],
        [1.2872, 0.4892]])
tensor([[2.2752, 3.4986],
        [1.2872, 0.4892]])
tensor([[2.2752, 3.4986],
        [1.2872, 0.4892]])


In [ ]:
# 내적
print(x)
print(y)

print(torch.matmul(x,y))
z = torch.mm(x,y)
print(z)
print(torch.svd(z))

tensor([[0.9514, 0.7460],
        [0.7653, 0.2723]])
tensor([[0.4182, 0.2132],
        [0.5946, 0.5566]])
tensor([[0.8414, 0.6181],
        [0.4819, 0.3148]])
tensor([[0.8414, 0.6181],
        [0.4819, 0.3148]])
torch.return_types.svd(
U=tensor([[-0.8759, -0.4825],
        [-0.4825,  0.8759]]),
S=tensor([1.1919, 0.0277]),
V=tensor([[-0.8134,  0.5817],
        [-0.5817, -0.8134]]))


### 텐서도 numpy처럼 인덱싱 형태로 사용 가능

In [ ]:
x = torch.Tensor([[1,2],
                  [3,4]])
print(x)
print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])

print(x[:,0])
print(x[:,1])

print(x[0,:])
print(x[1,:])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


### 간단한 pytorch neural network 연습

-'torch.nn.Moudle'을 통한 뉴럴 네트워크 생성

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc1 = nn.Linear(10, 20)  # 입력 10개 → 출력 20개
        self.fc2 = nn.Linear(20, 1)   # 입력 20개 → 출력 1개

    def forward(self, x):
        x = F.relu(self.fc1(x))  # 첫 번째 층을 거쳐 ReLU 활성화 함수 적용
        x = self.fc2(x)  # 두 번째 층을 거침 -> 출력되는 결과를 [5,1]에 맞추기 위한 작업
        return x

# 모델 생성
model = SimpleModel()

# 더미 데이터 생성 (배치 크기 5, 입력 크기 10)
x = torch.randn(5, 10)  # 5개의 샘플, 각 샘플은 10차원 벡터
print("x 출력")
print(x)

# 모델에 입력을 넣고 출력 확인
output = model(x)

print("입력 데이터 크기:", x.shape)      # torch.Size([5, 10])
print("출력 데이터 크기:", output.shape)  # torch.Size([5, 1])
print("출력 값:\n", output)

x 출력
tensor([[ 1.4521,  0.4594, -0.8011,  0.9129,  1.1030, -0.6153,  1.1064,  1.2202,
          0.7941,  0.1668],
        [-0.2032, -0.7687,  1.5264,  1.9405, -0.1879, -1.2843,  0.6292, -0.0604,
         -0.2144,  1.7202],
        [ 0.3023,  1.4758,  0.2007, -0.8937, -0.3759,  0.9897,  1.5580, -0.1859,
          0.2404, -2.2065],
        [ 0.5736, -0.9463, -0.9480,  1.2608, -0.7421, -0.2511,  0.1126, -0.8839,
         -0.3208,  0.3003],
        [ 0.1332,  1.6275,  2.9926,  0.2278, -1.5446, -2.2554, -0.3876,  0.1770,
         -0.4017, -1.8970]])
입력 데이터 크기: torch.Size([5, 10])
출력 데이터 크기: torch.Size([5, 1])
출력 값:
 tensor([[-0.1728],
        [-0.4849],
        [-0.1815],
        [-0.2045],
        [-0.6830]], grad_fn=<AddmmBackward0>)
